In [1]:
import numpy as np

Rank는 간단하게 말하자면 linearly independent한 column / rows의 갯수 입니다.
n x n 매트릭스가 있을 때, 모든 컬럼 벡터가 선형적으로 독립적인 경우 rank는 n이겠고, 만약 n개의 컬럼 벡터 중 중첩되는 한쌍이 있다면 rank의 갯수는 n-1이겠죠?

Week1 과 Week2에서 singular matrix에 대한 내용을 배웠는데요. 각각의 케이스에 대해서 살펴봅시다.

# non-singular matrix의 경우

먼저, 선형적으로 독립적인 (linearly independent)한 matrix A를 만듭니다.

In [50]:
A_mat = np.array([[1, 4, 0], [2, 2, 1], [3, 3, 0]])
A_mat

array([[1, 4, 0],
       [2, 2, 1],
       [3, 3, 0]])

위와 같이 각각의 컬럼은 독립적입니다. 따라서, rank의 갯수는 3개입니다. 실제 맞는지 확인해봅시다.

In [51]:
np.linalg.matrix_rank(A_mat)

3

자, 그렇다면 A^TA의 경우는 어떨까요?

In [53]:
AtA = A_mat.T.dot(A_mat)
AtA

array([[14, 17,  2],
       [17, 29,  2],
       [ 2,  2,  1]])

위와 같이 A^TA는 symmetric squared matrix이며, 모든 컬럼이 선형적으로 독립되어 있기때문에 rank는 3이며 마찬가지로 Full rank를 가집니다.

In [55]:
np.linalg.matrix_rank(AtA)

3

Full rank이니, non-singular matrix이고 그 뜻은 determinant가 0이 아니라는 것도 알 수 있습니다.

In [56]:
np.linalg.det(AtA)

81.000000000000028

또한, A^TA의 rank를 알아보는 방법으로는 대각선에 0이 아닌 eigenvalue (고유값)의 갯수의 합으로도 할 수 있습니다. A^TA의 eigenvalue를 구하는 방법으로는 eigen-decomposition과 SVD라는 방법이 있습니다. 각각의 방법을 사용해서 eigenvalue를 구해봅시다.

Eigen Decomposition

In [63]:
np.linalg.eig(AtA)[0]

array([ 40.27597124,   3.06865139,   0.65537737])

SVD (Singular Value Decomposition)

In [64]:
np.linalg.svd(AtA)[1]

array([ 40.27597124,   3.06865139,   0.65537737])

각 위와 같이 A^TA의 경우 symmetric squared matrix이기 때문에 두 방법 모두 활용 가능하며 같은 고유가 벡트를 반화해줍니다. 각각의 요소들 모두 0이 아니며, 따라서 rank는 3입니다.

마지막으로 Full rank인 경우, 역행력이 존재한다고 했었습니다. 한번 해볼까요?

In [85]:
np.linalg.inv(AtA)

array([[ 0.30864198, -0.16049383, -0.2962963 ],
       [-0.16049383,  0.12345679,  0.07407407],
       [-0.2962963 ,  0.07407407,  1.44444444]])

역행렬을 성공적으로 구했습니다 :)

# singular matrix의 경우

In [88]:
B_mat = np.array([[1, 1, 4, 4, 0], [2, 3, 2, 2, 1], [3, 3, 3, 3, 0], [4, 4, 4, 4, 0]])
B_mat

array([[1, 1, 4, 4, 0],
       [2, 3, 2, 2, 1],
       [3, 3, 3, 3, 0],
       [4, 4, 4, 4, 0]])

위의 matrix는 첫번째 두번째 컬럼이, 세번째 네벗째 컬럼이 같습니다. (이외에도 linear combination으로 의존도를 만들 수도 있습니다.)

rank는 몇일까요? 3개겠죠?

In [89]:
np.linalg.matrix_rank(B_mat)

3

In [90]:
BtB = B_mat.T.dot(B_mat)

In [91]:
np.linalg.matrix_rank(BtB)

3

이번에는 위와 마찬가지로 eigenvalue가 0이 아닌 것의 갯수로 rank를 확인 해봅시다.

In [92]:
np.linalg.svd(BtB)[1]

array([  1.46638228e+02,   8.24520416e+00,   1.11656793e+00,
         2.57656662e-15,   7.79827629e-19])

In [93]:
np.linalg.eig(BtB)[0]

array([  1.46638228e+02,   8.24520416e+00,   1.11656793e+00,
         4.90465314e-15,  -2.05605006e-18])

위 벡터를 보면 네번째, 다섯번째 고유값이 0인 것을 확인할 수 있습니다. (컴퓨터의 경우 numerical precision으로 인해서 완벽한 0이 나오지 않을 수 있습니다)

따라서, 고유값이 0이 아닌 갯수는 3이며 rank는 3입니다.

자, 그렇다면 determinant를 한번 볼까요? Full rank가 아니니 당연히 0이 나와야겠죠?

In [94]:
np.linalg.det(BtB)

0.0

자, 이번에는 week1과 week2에서 강조했듯이, singular matrix의 경우 역행력이 존재하지 않게되어 문제가 있다고 했었습니다. 한번 직접 해볼까요?

In [95]:
np.linalg.inv(BtB)

LinAlgError: Singular matrix

자, 위와 같이 에러가 나는군요. 맨 아래 에러 메시지를 확인해보면, LinAlgError: Singular matrix 라는 멘트가 나오네요. Singular matrix여서 역행렬을 구할 수 없다는군요! 그 뜻은 least square를 구할 수 없다는 말이기도 합니다.

이 경우 어떻게 하면 될까요? 그럼, 각 대각선에 작은 숫자를 더해서 고유값을 0이상으로 만들면 역행렬을 구할 수 있지 않을까요? 이것이 바로 ridge 입니다. 아래 한번 해봅시다 

In [109]:
delta_mat = 0.001 * np.eye(5)
delta_mat

array([[ 0.001,  0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.001,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.001,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.001,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.001]])

위와 같이 대각선에 작은 수를 가진 매트릭스를 만들었고, 이것을 BtB 매트릭스에 더해주겠습니다.

In [111]:
biased_BtB = BtB + delta_mat
biased_BtB

array([[ 30.001,  32.   ,  33.   ,  33.   ,   2.   ],
       [ 32.   ,  35.001,  35.   ,  35.   ,   3.   ],
       [ 33.   ,  35.   ,  45.001,  45.   ,   2.   ],
       [ 33.   ,  35.   ,  45.   ,  45.001,   2.   ],
       [  2.   ,   3.   ,   2.   ,   2.   ,   1.001]])

이 상태에서 eigenvalue 값을 봐볼까요?

In [113]:
np.linalg.svd(biased_BtB)[1]

array([  1.46639228e+02,   8.24620416e+00,   1.11756793e+00,
         1.00000000e-03,   1.00000000e-03])

모든 고유값이 0이 아니네요. 그렇다면 rank는 5이고 determinant는 0이 아니겠군요.

In [116]:
np.linalg.matrix_rank(biased_BtB)

5

In [117]:
np.linalg.det(biased_BtB)

0.0013513821559979647

자, 이번에는 역행력을 구해보겠습니다.

In [118]:
np.linalg.inv(biased_BtB)

array([[  3.33590409e+02,  -3.33433463e+02,  -4.73833398e-02,
         -4.73833399e-02,   3.32976128e+02],
       [ -3.33433463e+02,   3.33458688e+02,  -1.70455115e-02,
         -1.70455114e-02,  -3.33107849e+02],
       [ -4.73833399e-02,  -1.70455114e-02,   5.00028884e+02,
         -4.99971116e+02,   3.03378284e-02],
       [ -4.73833398e-02,  -1.70455115e-02,  -4.99971116e+02,
          5.00028884e+02,   3.03378285e-02],
       [  3.32976128e+02,  -3.33107849e+02,   3.03378285e-02,
          3.03378284e-02,   3.33916023e+02]])

이번에는 에러없이 역행렬을 구했습니다 :)

위 방법을 이용하여 우리는 singular matrix 형태의 데이터에 Linear model을 쓸 수 있게 되었고, 이 모델을 Ridge regression이라고 합니다.